version: '3'
services:
  rosmaster:
    image: alpineros/alpine-ros:melodic-ros-core
    container_name: rosmaster
    networks:
      - rosnet
    command: roscore
    ports:
      - "80:11311"
networks:
  rosnet:
    name: rosnet
    driver: bridge