version: '3'
services:
  rosmaster:
    image: alpineros/alpine-ros:melodic-ros-core
    container_name: rosmaster
    networks:
      - rosnet
    command: roscore
    ports:
      - "80:11311"

  talker:
    build: ../../
    container_name: talker
    networks:
      - rosnet
    environment:
      - ROS_HOSTNAME=talker
      - ROS_MASTER_URI=http://rosmaster:11311
    command: rosrun beginner_tutorials talker.py
    depends_on:
      - rosmaster

networks:
  rosnet:
    name: rosnet
    driver: bridge